<a href="https://colab.research.google.com/github/ahmadhajmosa/Machine-Learning-Lab-2020/blob/Mohamad-Al-Sayed/Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hello Github


# Lab on Machine Learning and Applications in Intelligent Vehicles
## Session 1: Introduction


### Course Plan:

This lab is a continuation to the Machine learning lecture, the objective of this course is to learn how to model and implement neural networks using deep learning python frameworks: 
1. Tensorflow
2. Keras
3. Pytorch

Useing these frameworks, we will go through the following topics and use cases:

#### Session 1: 05.06 - 09:00 - 11:00  :

>#### Presentation:  05.06 - 09:00 - 10:30:
>1. Introduction to deep learning frameworks
2. Deep learning in Numpy

>#### Break:  05.06 - 10:30 - 10:45
>#### Assignment:  05.06 - 10:45 - 11:45 : 
>* Implementation of backprop using numpy

>1. Tensorflow backround 
2. Implementation of feedforward neural networks using Tensorflow

>#### Break:  05.06 - 10:00 - 10:15
>#### Assignment:  05.06 - 10:15 - 10:45 : 
  
  >* play around with tensorflow and build your first neural network



#### Session 2:  05.06 - 11:00 - 12:00  :

>#### Presentation:  05.06 - 11:00 - 12:00:


>3. Implementation of CNN useing Tensorflow
4. Tensorboard

>#### Break:  05.06 - 12:00 - 13:00
>#### Assignment:  05.06 - 13:00 - 13:30 :


 #### Session 3:  05.06 - 13:30 - 15:00  :

>#### Presentation:  05.06 - 13:00 - 14:00:

>5. Introduction to Keras
6. CNN using Keras
>#### Break:  05.06 - 14:00 - 14:15
>#### Assignment:  05.06 - 14:15 - 14:45 :

 #### Session 4:  05.06 - 15:00 - 16:30  :

>#### Presentation:  05.06 - 15:00 - 15:45:

>7. LSTM using Keras

>#### Break:  05.06 - 15:45 - 16:00
>#### Assignment:  05.06 - 16:00 - 16:30 :


8. VGG, Inceptaion, ResNet models using Keras

9. Autoencoders using Keras

10. Sequence to Sequence Models using Keras 

11. Attention Mechanism using Keras
12. GANS 
13. Introduction to Pytorch
14. Machine translation using Pytorch
15. Introduction to Allennlp
16. Deep Reinforcment Learning using Keras
17. Use case: building self driving car using Unity and tensorflow










#Session 1: 05.06 - 09:00 - 11:00 :




## Deep learning frameworks:

In the past decade, many deep learning frameworks have been developed to ease and scale the research and development of AI. Many big technology providers including Google, IBM, Microsoft and Facebook have entered the race to provide the best and most popluar frameworks. To enter such a race, mainly four features are considered in the provided framework:

1. Uses a popular language for data scientists (Python, Scale, C++ or R)
2. Flexible in creating and adjusting deep learning architectures -> Functional programming
3. Easy for computing gradients
4. Interface with GPUs for parallel processing


In the following we see the most popular provided deep learning frameworks with their providers
https://towardsdatascience.com/deep-learning-framework-power-scores-2018-23607ddf297a

![alt text](https://cdn-images-1.medium.com/max/1600/1*dYjDEI0mLpsCOySKUuX1VA.png)

## Tensorflow
TensorFlow is the undisputed heavyweight champion. It has the most GitHub activity, Google searches, Medium articles, books on Amazon and ArXiv articles. It also has the most developers using it and is listed in the most online job descriptions. TensorFlow is backed by Google.

## Keras
Keras has an “API designed for human beings, not machines.” It is the second most popular framework in nearly all evaluation areas. Keras sits on top of TensorFlow, Theano, or CNTK. Start with Keras if you are new to deep learning.

## Pytorch

PyTorch is the third most popular overall framework and the second most popular stand-alone framework. It is younger than TensorFlow and has grown rapidly in popularity. It allows customization that TensorFlow does not. It has the backing of Facebook.

## Theano

Theano was developed at the University of Montreal in 2007 and is the oldest significant Python deep learning framework. It has lost much of its popularity and its leader stated that major releases were no longer on the roadmap. However, updates continue to be made. Theano still the fifth highest scoring framework.

# Comparision:

## Criteria 1: Online Job Listings

TensorFlow is the clear winner when it comes to frameworks mentioned in job listings. Learn it if you want a job doing deep learning.

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*kA8dIgRqLdWgKgs2sd7clA.png)

## Criteria 2: Usage


Keras showed a surprising amount of use — nearly as much as TensorFlow. It’s interesting that US employers are overwhelmingly looking for TensorFlow skills, when — at least internationally — Keras is used almost as frequently.

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*6b2Tm0oFr99zKaxkr4g52w.png)
  
  
## Criteria 4: Google Search Activity

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*wpA6C9x_Nri42EzbqnS1fQ.png)

## Criteria 5: Medium Articles

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*Y1cJUgZTC3u_hU1lmdsroQ.png)


## Criteria 6: Amazon Books

>> ![alt text](https://cdn-images-1.medium.com/max/800/1*mtP47q29T6agdkEoJcCw-w.png)

## Criteria 7 : ArXiv Articles

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*7jdNoNkGlx_1EnfevQXRvw.png)
  
## Criteria 8: GitHub Activity

  >> ![alt text](https://cdn-images-1.medium.com/max/800/1*eOOYV3C5klsuVBMX31ngxw.png)
  
 --------------------------------
 


  
 








```
# This is formatted as code
```


Before we jump into Tensorflow, we will implemented our first neural network model using Python Numpy package. NumPy is the fundamental package for scientific computing with Python, such as:

1. Linear Algebra
2. Statistics
3. Calculus

## A brief intro to Numpy operations:

1. Creating a Vector:
Here we use Numpy to create a 1-D Array which we then call a vector.





In [1]:
#Load Library
#numpy backend is C++ that's why it is faster than other libraries
import numpy as np

#Create a vector as a Row
vector_row = np.array([1,2,3])

#Create vector as a Column
vector_column = np.array([[1],[2],[3]])

In [6]:
display(vector_row.shape) # 1 row and three columns
display(vector_column.shape)# 3 rows and 1 column
display(type(vector_column))

(3,)

(3, 1)

numpy.ndarray

2. Creating a Matrix
We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [7]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [15]:
display(vector_row[0]) # 0 is the index of the first value 
display(vector_row[-1]) # -1 is the index of the last value
display(vector_row[:2]) # take the first two values from vector_row
display(vector_row[2:]) #take the values from the third till the end

1

6

array([1, 2])

array([3, 4, 5, 6])

3. Selecting Elements


In [12]:
#Load Library
import numpy as np

#Create a vector as a Row
vector_row = np.array([ 1,2,3,4,5,6 ])

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Select 3rd element of Vector
print("3d element of vector row is:"+str(vector_row[2]))
#Select 2nd row 2nd column
print(matrix[1,1])
#Select all elements of a vector
print(vector_row[:])
#Select everything up to and including the 3rd element
print(vector_row[:3])
#Select the everything after the 3rd element
print(vector_row[3:])
#Select the last element
print(vector_row[-1])
#Select the first 2 rows and all the columns of the matrix
print(matrix[:2,:])
#Select all rows and the 2nd column of the matrix
print(matrix[:,1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
3d element of vector row is:3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


4. Describing a Matrix

In [ ]:
import numpy as np


#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
#View the Number of Rows and Columns
print(matrix.shape)
#View the number of elements (rows*columns)
print(matrix.size)
#View the number of Dimensions(2 in this case)
print(matrix.ndim)

5. Finding the max and min values

In [16]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Return the max element
print(np.max(matrix))
#Return the min element
print(np.min(matrix))
#To find the max element in each column
print(np.max(matrix,axis=0))
#To find the max element in each row
print(np.max(matrix,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[7 8 9]
[3 6 9]


6. Reshaping Arrays


In [22]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Reshape
print(matrix.reshape(9,1))
#Reshaping to (1,9) is also possible
#the final size needs to be equal before and after shaping the matrix
print(matrix.reshape(1,9))
print(matrix.reshape(3,-1))

#Here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))
#If we provide only 1 value Reshape would return a 1-d array of that length
print(matrix.reshape(9))
#We can also use the Flatten method to convert a matrix to 1-d array
print(matrix.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


7. Calculating Dot Products

In [24]:
#Load Library
import numpy as np

#Create vector-1
vector_1 = np.array([ 1,2,3 ])
#Create vector-2
vector_2 = np.array([ 4,5,6 ])
#Calculate Dot Product
print(np.dot(vector_1,vector_2))
#4+10+18 =32
#Alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)

32
32


##Linear regression in Numpy:

---



Write the numpy code for the following model:

$Y=WX+B$

where $X$ is 3x10 matrix:  10 samples and 3 features

$Y$ is 4x10 matrix: 10 samples and 4 outputs

$W$ is the weights matrix with the shape 4x3: connecting 3 inputs to 4 outputs

$b$ is a vector with a size 4 ( one bias per output)


In [26]:
#Load Library
import numpy as np

# Generate a random X (we do not have a real data)

X = np.random.rand(3,10)# 3 rows and 10 columns of random numbers
display(X)
display(X.shape)

# Generate a random weights vector
W = np.random.rand(4,3)
# 4 is the dimension of the output and 3 represents the number of inputs.
#Could be reverse, it depends on the way we model

# Generate a random bias 
#number of bias = number of neurons
b = np.random.rand(4,1)

# Calculate Y
Y= np.dot(W,X) + b
display(Y)
display(Y.shape)


array([[0.5840422 , 0.99427279, 0.02934036, 0.30711559, 0.51772824,
        0.09849207, 0.01703363, 0.35055659, 0.45478349, 0.06834479],
       [0.50502536, 0.27983585, 0.66075648, 0.95788112, 0.65382128,
        0.41198729, 0.34603137, 0.41682609, 0.56477196, 0.22683765],
       [0.15612819, 0.60196889, 0.307691  , 0.27534929, 0.31232238,
        0.74094751, 0.29072798, 0.57872528, 0.97623745, 0.17513792]])

(3, 10)

array([[1.73412983, 2.11608642, 1.53851396, 2.02285161, 1.9203743 ,
        1.6207945 , 1.2166439 , 1.72481921, 2.1931732 , 1.07187738],
       [0.71477899, 0.75980593, 0.86104683, 1.18220524, 0.92706985,
        0.82722965, 0.53757529, 0.79214153, 1.14198433, 0.37174635],
       [1.29937964, 1.58074268, 1.52324573, 1.82905277, 1.59387417,
        1.71758059, 1.19031071, 1.59817233, 2.15809179, 0.96364403],
       [0.94177161, 0.82987654, 1.02112159, 1.23109711, 1.04223295,
        0.87534922, 0.81165197, 0.88603805, 1.003323  , 0.73141671]])

(4, 10)

In [35]:
X = np.array([[1,0,1],[1,0,0]]) # the input here is 2x3
W = np.array([[2,4],[6,5],[3,5],[10,3]])#the weights are 4x2
#the output Y should then be: 4x3
Y= np.dot(W,X) + b
print("the output Y of the dot product is: Y=\n"+str(Y))
print(X.shape)
print(W.shape)
print(Y.shape)

the output Y of the dot product is: Y=
[[ 6.6928397   0.6928397   2.6928397 ]
 [11.05323549  0.05323549  6.05323549]
 [ 8.55223348  0.55223348  3.55223348]
 [13.57161482  0.57161482 10.57161482]]
(2, 3)
(4, 2)
(4, 3)


## One neuron model in numpy:

A single neuron has multiple inputs and one output, in addition to the linear regression model, we need to add non linearity through an activation function:

$Y= f(WX+B)$

where $X$ is n x m matrix:  m samples and n features/inputs

$f(g)= \frac{1}{1+\exp(-g)}$  is a sigmoid acitavation function

$Y$ is nh1 x m matrix: m samples and ny outputs

$W$ is the weights matrix with the shape nh1 x n: connecting 3 inputs to 4 outputs

$b$ is a vector with a size nh1 ( one bias per output)





In [36]:
# load Library
import numpy as np 

#this is how we define the activation function
f = lambda x: 1.0/(1.0 + np.exp(-x)) 
# activation function (use sigmoid)

# Generate a random X (we do not have a real data)
X = np.random.rand(3,10)


# Generate a random weights vector
W = np.random.rand(1,3)


# Generate a random bias 
b = np.random.rand()

# Calculate Y
Y= f(np.dot(W,X) + b)
display(Y)
#each element value represents with how much the neuron is activated

array([[0.78775749, 0.71431091, 0.72433555, 0.62595953, 0.69248928,
        0.76062288, 0.71023648, 0.73092367, 0.64587678, 0.75540469]])

## One hidden layer model in numpy:

The difference from the one neuron model is simple:  we need only to change the number of output "ny"

In [39]:
# load Library
import numpy as np 

#Suppose we have the following NN architecture

m = 10 # Number of samples
ni= 3 # Number of input neurons
h = 1 # Number of hidden layers
nh1 = 4 # Number of neurons in the hidden layer 1
no =1 # Number of neurons in the output layer



f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)

# Generate a random X (we do not have a real data)
X = np.random.rand(ni,m)


# Generate a random weights vector for the first hidden layer
W1 = np.random.rand(nh1,ni)


# Generate a random bias for the first hidden layer 
b1 = np.random.rand(nh1,1)

# Generate a random weights vector for the output layer
W2 = np.random.rand(no,nh1)

# Generate a random bias for the output layer 
b2 = np.random.rand(no,1)

# Calculate output of the first hidden layer
Yh1= f(np.dot(W1,X) + b1)

# Calculate output of the output layer

Y= f(np.dot(W2,Yh1) + b2)

display(Yh1.shape)
display(Y.shape)

(4, 10)

(1, 10)

In [45]:
# 2 hidden layers
# load Library
import numpy as np 

#Suppose we have the following NN architecture

m = 10 # Number of samples
ni= 3 # Number of input neurons
h = 2 # Number of hidden layers
nh1 = 4 # Number of neurons in the hidden layer 1
nh2 = 5 # Number of neurons in the second hidden layer
no =1 # Number of neurons in the output layer
# activation function (use sigmoid)
f = lambda x: 1.0/(1.0 + np.exp(-x)) 

# Generate a random X (we do not have a real data)
X = np.random.rand(ni,m)

##################################################################
# Generate a random weights vector for the first hidden layer
W1 = np.random.rand(nh1,ni)
# Generate a random bias for the first hidden layer 
b1 = np.random.rand(nh1,1)
# Calculate output of the first hidden layer
Yh1= f(np.dot(W1,X) + b1)

##################################################################
# Generate a random weights vector for second hidden layer
W2 = np.random.rand(nh2,nh1)
# Generate a random bias for second hidden layer
b2 = np.random.rand(nh2,1)
# Calculate output of the first hidden layer
Yh2= f(np.dot(W2,Yh1) + b2)
print("debugging")
##################################################################
# Generate a random weights vector for the output layer
W3 = np.random.rand(no,nh2)
# Generate a random bias for the output layer 
b3 = np.random.rand(no,1)
# Calculate output of the output layer
Y= f(np.dot(W3,Yh2) + b3)

display(Yh1.shape)
display(Yh2.shape)
display(Y.shape)

heyyyyyyyyyyyyyy


(4, 10)

(5, 10)

(1, 10)

In [46]:
# 3 hidden layers
# load Library
import numpy as np 

#Suppose we have the following NN architecture

m = 10 # Number of samples
ni= 3 # Number of input neurons
h = 2 # Number of hidden layers
nh1 = 4 # Number of neurons in the hidden layer 1
nh2 = 5 # Number of neurons in the second hidden layer
nh3 = 7 #number of neurons in the 3d hidden layer
no =1 # Number of neurons in the output layer
# activation function (use sigmoid)
f = lambda x: 1.0/(1.0 + np.exp(-x)) 

# Generate a random X (we do not have a real data)
X = np.random.rand(ni,m)

##################################################################
# Generate a random weights vector for the first hidden layer
W1 = np.random.rand(nh1,ni)
# Generate a random bias for the first hidden layer 
b1 = np.random.rand(nh1,1)
# Calculate output of the first hidden layer
Yh1= f(np.dot(W1,X) + b1)

##################################################################
# Generate a random weights vector for second hidden layer
W2 = np.random.rand(nh2,nh1)
# Generate a random bias for second hidden layer
b2 = np.random.rand(nh2,1)
# Calculate output of the first hidden layer
Yh2= f(np.dot(W2,Yh1) + b2)
print("debugging")
##################################################################

##################################################################
# Generate a random weights vector for second hidden layer
W3 = np.random.rand(nh3,nh2)
# Generate a random bias for second hidden layer
b3 = np.random.rand(nh3,1)
# Calculate output of the first hidden layer
Yh3= f(np.dot(W3,Yh2) + b3)
print("debugging")
##################################################################
# Generate a random weights vector for the output layer
W4 = np.random.rand(no,nh3)
# Generate a random bias for the output layer 
b4 = np.random.rand(no,1)
# Calculate output of the output layer
Y= f(np.dot(W4,Yh3) + b4)

display(Yh1.shape)
display(Yh2.shape)
display(Yh3.shape)
display(Y.shape)

debugging
debugging


(4, 10)

(5, 10)

(7, 10)

(1, 10)

## Gradient descent in Numpy:
Let us now start training a neural network
We start by implementing a simple gradient descent for linear regression

In [ ]:
import numpy as np
W1 = np.random.rand(10,2)
W1

array([[0.51448509, 0.18163591],
       [0.59599079, 0.50199117],
       [0.10763886, 0.82440073],
       [0.71248353, 0.75820124],
       [0.16277352, 0.25229085],
       [0.27725862, 0.93018921],
       [0.3939125 , 0.89440869],
       [0.34771914, 0.55332989],
       [0.57875705, 0.50764801],
       [0.68848694, 0.60201835]])

In [49]:
import numpy as np
converged = False
iter = 0
m = 10 # Number of samples
ni= 1 # Number of input neurons
h = 1 # Number of hidden layers
no =1 # Number of neurons in the output layer

# Generate a random X (we do not have a real data)
X = np.random.rand(m)
display(X)

# learning rate
# learning rate represents the steps to go to the minimum
#high learning rate: big steps
#low learning rate: baby steps towards the minimum
alpha =0.01

# early stop criteria 
#to prevent the model from overfitting
#if the error change is less than ep
ep=0.001

# maximum number of training iterations
#so we update the weights 100 times
max_iter=100
# w_t+1 = w_t - lr*dJ/dw

# Generate a random weights vector for the output layer
W1 = np.random.rand()

# Generate a random bias for the output layer 
b1 = np.random.rand()

# Generate a random ground truth
Y_gr = np.random.rand(m)

# Y_gr = WX + b

# J(W,b) = sum(((WX+b) - Y_gr)^2)
#Sum of squared error
J = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)])
print('J1', J)
J = 0
#Another way to do the function is:
for i in range(m):
  J+= (b1+ W1*X[i] - Y_gr[i])**2
print('J2', J)
#convergence means when we meet our goal
while not converged:
        # for each training sample, compute the gradient (d/d_theta j(theta))
        grad0 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i]) for i in range(m)]) 
        grad1 = 1.0/m * sum([(b1 + W1*X[i] - Y_gr[i])*X[i] for i in range(m)])
        
        # update the theta_temp
        temp0 = W1 - alpha * grad0
        temp1 = b1 - alpha * grad1
        # update theta
        W1 = temp0
        b1 = temp1
        
        # sum squared error
        e = sum([(b1 + W1*X[i] - Y_gr[i])**2 for i in range(m)]) 
        #print(e)
        if abs(J-e) <= ep:
            print('Converged, iterations: ', iter, '!!!')
            converged = True
    
        J = e   # update error 
        iter += 1  # update iter
    
        if iter == max_iter:
            print('Max interactions exceeded!')
            converged = True

array([0.10564688, 0.15023793, 0.48104107, 0.87134807, 0.16119536,
       0.55633108, 0.17324777, 0.97690501, 0.8732754 , 0.84601702])

J1 1.7427830283272854
J2 1.7427830283272854
Max interactions exceeded!


##Assignment 1
### Backpropagation in Numpy:


In [50]:

num_inputs = 4
hidden_layer_1_outputs = 4
hidden_layer_2_outputs = 3

num_samples = 10

f = lambda x: 1.0/(1.0 + np.exp(-x)) # activation function (use sigmoid)


X = np.random.rand(num_samples,num_inputs-1) # 10x3

X = np.hstack((np.ones((X.shape[0], 1)), X)) # 10x4

display(X.shape)

# Generate a random weights vector for the first hidden layer
W_h1 = np.random.rand(num_inputs,hidden_layer_1_outputs) # 4x4
# O     O     O 
# O     O     O
# O     O     O
# O     O    


# Generate a random weights vector for the second hidden layer
W_h2 = np.random.rand(hidden_layer_1_outputs+1,hidden_layer_2_outputs)


# Calculate output of hidden layer 1
h1= f(np.dot(X,W_h1))
display(h1.shape)

# Calculate output of hidden layer 2
#h2= f(np.dot(h1,W_h2))
#display(h2.shape)


# learning rate
alpha =0.01

# early stop criteria 
ep=0.001


# maximum number of training iterations
max_iter=100

# Generate a random ground truth
Y_gr = np.random.rand(hidden_layer_2_outputs,num_samples)

#J = sum([(h2 - Y_gr[:,i])**2 for i in range(num_samples)]) #cost function sum of squared error
print(J)

#while not converged:
for i in range(100):
        #print('Interations:' , iter)
    
        # forward prop   
        # Calculate output of hidden layer 1
        h1= f(np.dot(X,W_h1))
        
        # append a column with ones representing bias inputs
        h1 = np.hstack((np.ones((h1.shape[0], 1)), h1))
        # Calculate output of hidden layer 2
        h2= f(np.dot(h1,W_h2))
        
        
        #error/error 
               
        J = np.sum(np.square(h2- Y_gr.T))
        
        # gradient of the output layer
        grad_h2 = h2*J
    
        
        # error    
        #display('h1', (h1[:, 1:] * (1 - h1[:, 1:])).shape)    
        #display('dot ', np.dot(grad_h2, W_h2.T[:, 1:]).shape)


        hidden_error = (h1[:, 1:] * (1 - h1[:, 1:])) * np.dot(grad_h2, W_h2.T[:, 1:]) 

        #print(h1.shape)
        #print(hidden_error.shape)
        #gradient of the hidden layer 1
        #np.newaxis is used to increase the dimension of the existing array by one more dimension, when used once.
        grad_h1= h1[:, :, np.newaxis]*hidden_error[:, np.newaxis, :]

      
        # average gradient
        total_output_gradient_h2 = np.average(grad_h2, axis=0)
        total_hidden_gradient_h1 = np.average(grad_h1, axis=0)
        #print(grad_h1.shape)
        #print(W_h1.shape)

        # update weights
        W_h2 += - alpha * total_output_gradient_h2
        W_h1 += - alpha * total_hidden_gradient_h1[1:,:]
        
        
        print('iter',i)
        
        print('cost',J)

        
        


        
        
        
        
        
              
        


(10, 4)

(10, 4)

1.918736883374265
iter 0
cost 7.070918726763268
iter 1
cost 6.5979277199397535
iter 2
cost 6.105861342460266
iter 3
cost 5.617280009095367
iter 4
cost 5.150944889904443
iter 5
cost 4.719751674644593
iter 6
cost 4.330670627203531
iter 7
cost 3.9858906838070727
iter 8
cost 3.6843316483212365
iter 9
cost 3.4230069226395634
iter 10
cost 3.1980387228073073
iter 11
cost 3.005321266896414
iter 12
cost 2.8409062995358974
iter 13
cost 2.7011977771964872
iter 14
cost 2.5830275935796636
iter 15
cost 2.4836633188141235
iter 16
cost 2.4007808269548474
iter 17
cost 2.33242155905602
iter 18
cost 2.2769455306193387
iter 19
cost 2.2329858653668455
iter 20
cost 2.1994075174046577
iter 21
cost 2.1752711050986147
iter 22
cost 2.1598018673883916
iter 23
cost 2.15236331640683
iter 24
cost 2.152434986999241
iter 25
cost 2.1595936497263972
iter 26
cost 2.173497388462891
iter 27
cost 2.193872007851724
iter 28
cost 2.2204993091655285
iter 29
cost 2.253206845523345
iter 30
cost 2.29185883465231
iter 31
cost 2.33